"""
AntDir environment for Gymnasium.

Based on the VariBAD AntDir task:
https://github.com/lmzintgraf/varibad/blob/master/environments/mujoco/ant_dir.py

The ant receives rewards for running in a target direction (forward or backward).
Tasks are generated by sampling directions from {-1.0, 1.0} (backward/forward).
"""

import random
import numpy as np
import gymnasium as gym
from gymnasium import spaces
from gymnasium.envs.mujoco.ant_v5 import AntEnv


class AntDirEnv(AntEnv):
    """Ant environment with target direction.
    
    The ant follows MuJoCo dynamics and receives rewards composed of:
    - A reward proportional to velocity in the target direction
    - A control cost penalty
    - A contact cost penalty
    - A healthy reward
    
    Tasks are sampled from {-1.0, 1.0} representing backward/forward direction.
    """

    def __init__(self, max_episode_steps=1000, **kwargs):
        self._max_episode_steps = max_episode_steps
        # Default to excluding contact forces, but allow override via kwargs
        kwargs.setdefault('include_cfrc_ext_in_observation', False)
        super().__init__(**kwargs)

        self.task_dim = 1
        self.goal_direction = 1.0  # Will be set properly in reset_task
        
        # Set initial task
        self.reset_task()

    def step(self, action):
        xy_position_before = self.data.qpos[0:2].copy()
        self.do_simulation(action, self.frame_skip)
        xy_position_after = self.data.qpos[0:2].copy()

        xy_velocity = (xy_position_after - xy_position_before) / self.dt
        x_velocity, y_velocity = xy_velocity

        # Reward for moving in the goal direction (along x-axis)
        forward_reward = self.goal_direction * x_velocity

        # Standard Ant costs
        ctrl_cost = self.control_cost(action)
        contact_cost = self.contact_cost

        # Survival/healthy reward
        healthy_reward = self.healthy_reward

        rewards = forward_reward + healthy_reward
        costs = ctrl_cost + contact_cost

        reward = rewards - costs
        
        # Check termination based on healthy state
        terminated = not self.is_healthy if hasattr(self, 'is_healthy') else False
        
        observation = self._get_obs()

        info = {
            'reward_forward': forward_reward,
            'reward_ctrl': -ctrl_cost,
            'reward_contact': -contact_cost,
            'reward_survive': healthy_reward,
            'x_position': xy_position_after[0],
            'y_position': xy_position_after[1],
            'distance_from_origin': np.linalg.norm(xy_position_after, ord=2),
            'x_velocity': x_velocity,
            'y_velocity': y_velocity,
            'forward_reward': forward_reward,
            'task': self.goal_direction,
        }

        if self.render_mode == "human":
            self.render()

        return observation, reward, terminated, False, info

    def reset_task(self, task=None):
        """Reset the task (goal direction).
        
        Args:
            task: If provided, set to this task. Otherwise sample randomly from {-1.0, 1.0}
        """
        if task is None:
            self.goal_direction = random.choice([-1.0, 1.0])
        else:
            self.goal_direction = task

    def get_task(self):
        """Return the current task (goal direction)."""
        return np.array([self.goal_direction])

    def set_task(self, task):
        """Set the task to a specific value."""
        self.goal_direction = float(task)

    def sample_tasks(self, num_tasks):
        """Sample a batch of tasks.
        
        Args:
            num_tasks: Number of tasks to sample
            
        Returns:
            Array of shape (num_tasks, task_dim) with sampled directions
        """
        directions = np.random.choice([-1.0, 1.0], size=num_tasks)
        return directions.reshape(-1, 1)
