"""
HalfCheetahDir environment for Gymnasium.

Based on the VariBAD HalfCheetahDir task:
https://github.com/lmzintgraf/varibad/blob/master/environments/mujoco/half_cheetah_dir.py

The half-cheetah receives rewards for running in a target direction (forward or backward).
Tasks are generated by sampling directions from {-1.0, 1.0} (backward/forward).
"""

import random
import numpy as np
import gymnasium as gym
from gymnasium import spaces
from gymnasium.envs.mujoco.half_cheetah_v5 import HalfCheetahEnv


class HalfCheetahDirEnv(HalfCheetahEnv):
    """Half-cheetah environment with target direction.
    
    The half-cheetah follows MuJoCo dynamics and receives rewards composed of:
    - A reward proportional to velocity in the target direction
    - A control cost penalty
    
    Tasks are sampled from {-1.0, 1.0} representing backward/forward direction.
    """

    def __init__(self, max_episode_steps=200, **kwargs):
        self._max_episode_steps = max_episode_steps
        self.task_dim = 1
        self.goal_direction = 1.0  # Will be set properly in reset_task
        super().__init__(**kwargs)
        # Set initial task
        self.reset_task()

    def step(self, action):
        xposbefore = self.data.qpos[0]
        self.do_simulation(action, self.frame_skip)
        xposafter = self.data.qpos[0]

        forward_vel = (xposafter - xposbefore) / self.dt
        forward_reward = self.goal_direction * forward_vel
        ctrl_cost = 0.5 * 1e-1 * np.sum(np.square(action))

        observation = self._get_obs()
        reward = forward_reward - ctrl_cost
        terminated = False
        truncated = False
        info = {
            'reward_forward': forward_reward,
            'reward_ctrl': -ctrl_cost,
            'task': self.get_task()
        }
        
        return observation, reward, terminated, truncated, info

    def sample_tasks(self, n_tasks):
        """Sample n_tasks random tasks (forward/backward direction)."""
        return [random.choice([-1.0, 1.0]) for _ in range(n_tasks)]

    def set_task(self, task):
        """Set the current task (direction)."""
        if isinstance(task, np.ndarray):
            task = task[0]
        self.goal_direction = task

    def get_task(self):
        """Get the current task."""
        return np.array([self.goal_direction])

    def reset_task(self, task=None):
        """Reset the task to a new one or the provided task."""
        if task is None:
            task = self.sample_tasks(1)[0]
        self.set_task(task)
        return task
